### PR TITLE
KeePass importer (using kppy)

### PR DESCRIPTION
**Pull request by costypetrisor**
Trying to fulfill #32. I tested only on Linux

### CODE REVIEW

**Comment by marcwebbie** [comment]
This looks exciting. Are you having troubles running on python 3?

**Comment by costypetrisor** [comment]
no, importing works fine on Python3.
I just forgot to submit that 1 string typo: I was writing in a file object with a str object (f.write('bad_db')), but forgot to add the b'' to the string  so it would work on Python3

**Comment by costypetrisor** [comment]
:( looks like PyCrypto has distribution issues on Python3 and Windows.
I'll look at this sometime later today.

**Comment by marcwebbie** [comment]
Hello @costypetrisor ,

What about start importing *plain text* `keepass` credentials.

1. Someone that uses keepass export its credentials to plain text as `plain.txt`
2. She runs `passpie import plain.txt`
3. She sees her credentials listed: `passpie`

Thanks for your contribution!

**Comment by costypetrisor** [comment]
Hi,
Allow me a bit of time this weekend to try to hack some things. Maybe I can make it work.
Costy

**Comment by costypetrisor** [comment]
@marcwebbie 
Hi,

Can you take another look at the changes :) ? Everything should work now.

Thanks,
Costy

**Comment by marcwebbie** [comment]
Hellow @costypetrisor 

It is looking great. I am working on some rewriting to remove some dependencies like I removed `pyperclip` and `gitpython`. I've been thinking about getting the importers as external projects.

Something like pytest extensions. 

You could maybe get this code into a project called `passpie-keepass` and update the README pointing to your repository. What do you think?

Thanks for your contributions

**Comment by costypetrisor** [comment]
Hi @marcwebbie ,

I will do this most probably tomorrow.

Thanks,
Costy

**Comment by krzkrzkrz** [comment]
Any luck on this?

**Comment by costypetrisor** [comment]
@krzkrzkrz : You could try to install the latest passpie from github and then install https://github.com/costypetrisor/passpie_keepass 

Marc Webbie suggested to add support for plugins for passpie(similar to pytest plugins, they work through setuptools entrypoints). This was merged in #65. I'll close this PR because it's no longer needed.

@marcwebbie you suggested in #65 that I should update the README about the plugin support. I will do this in the coming 2-3 days. After that I'll wait for an official passpie release on PyPI and then I'll release passpie_keepass on PyPI too, but requiring the passpie release which supports plugins.

**Comment by krzkrzkrz** [comment]
@costypetrisor Unfortunately, the documentation for https://passpie-keepass.readthedocs.org/ points to a 404 page. I opened up an issue for that. Do the other plugins (you mentioned) work to import keepass passwords?

**Pull request closed without merging**
